{
"money": {"description": "货币配置表", "output": "../../doc/trunk/game_server/data_money.config", "workbook": "../../doc/trunk/RE0_item.xlsm", "sheet": "data_item", "label": 5, "begin": 6, "primkey": "type_id", "syntax": "off"}
, "section": {"description": "关卡配置表", "output": "../../doc/trunk/game_server/data_section.config", "workbook": "../../doc/trunk/RE0_section.xlsm", "sheet": "data_section", "label": 5, "begin": 6, "primkey": "section_id", "syntax": "off"}
, "chapter": {"description": "章节配置表", "output": "../../doc/trunk/game_server/data_chapter.config", "workbook": "../../doc/trunk/RE0_chapter.xlsm", "sheet": "data_chapter", "label": 5, "begin": 6, "primkey": "chapter_id", "syntax": "off"}
, "monster": {"description": "怪物配置表", "output": "../../doc/trunk/game_server/data_monster.config", "workbook": "../../doc/trunk/RE0_monster.xlsm", "sheet": "data_monster", "label": 5, "begin": 6, "primkey": "type_id", "syntax": "off"}
, "drop": {"description": "掉落配置表", "output": "../../doc/trunk/game_server/data_drop.config", "workbook": "../../doc/trunk/RE0_drop.xlsm", "sheet": "data_drop", "label": 5, "begin": 6, "primkey": "drop_id", "syntax": "off"}
, "role": {"description": "角色配置表", "output": "../../doc/trunk/game_server/data_ger.config", "workbook": "../../doc/trunk/RE0_role.xlsm", "sheet": "data_role", "label": 5, "begin": 6, "primkey": "type_id", "syntax": "off"}
, "role_break": {"description": "角色突破配置表", "output": "../../doc/trunk/game_server/data_ger_breakout.config", "workbook": "../../doc/trunk/RE0_role_break.xlsm", "sheet": "data_role_break", "label": 5, "begin": 6, "primkey": "primkey", "syntax": "off"}
, "role_uplevel": {"description": "角色强化配置表", "output": "../../doc/trunk/game_server/data_ger_uplevel.config", "workbook": "../../doc/trunk/RE0_role_uplevel.xlsm", "sheet": "data_role_uplevel", "label": 5, "begin": 6, "primkey": "primkey", "syntax": "off"}
, "equip_uplevel": {"description": "装备强化配置表", "output": "../../doc/trunk/game_server/data_equip_uplevel.config", "workbook": "../../doc/trunk/RE0_equip_uplevel.xlsm", "sheet": "data_equip_uplevel", "label": 5, "begin": 6, "primkey": "primkey", "syntax": "off"}
, "equip_break": {"description": "装备突破配置表", "output": "../../doc/trunk/game_server/data_equip_breakout.config", "workbook": "../../doc/trunk/RE0_equip_break.xlsm", "sheet": "data_equip_break", "label": 5, "begin": 6, "primkey": "primkey", "syntax": "off"}
, "role_upskill": {"description": "角色技能强化配置表", "output": "../../doc/trunk/game_server/data_ger_upskill.config", "workbook": "../../doc/trunk/RE0_role_upskill.xlsm", "sheet": "data_role_upskill", "label": 5, "begin": 6, "primkey": "primkey", "syntax": "off"}
, "card": {"description": "强化卡配置表", "output": "../../doc/trunk/game_server/data_card.config", "workbook": "../../doc/trunk/RE0_qianghuacard.xlsm", "sheet": "data_qianghuacard", "label": 5, "begin": 6, "primkey": "type_id", "syntax": "off"}
, "lucky_bastard": {"description": "抽卡配置表", "output": "../../doc/trunk/game_server/data_box.config", "workbook": "../../doc/trunk/RE0_lucky_bastard.xlsm", "sheet": "data_lucky_bastard", "label": 5, "begin": 6, "primkey": "pool_id", "syntax": "off"}
, "role_intimacy": {"description": "好感度配置表", "output": "../../doc/trunk/game_server/data_intimacy.config", "workbook": "../../doc/trunk/RE0_role_intimacy.xlsm", "sheet": "data_role_intimacy", "label": 5, "begin": 6, "primkey": "primkey", "syntax": "off"}
, "player_level": {"description": "玩家等级配置表", "output": "../../doc/trunk/game_server/data_player_level.config", "workbook": "../../doc/trunk/RE0_player_level.xlsm", "sheet": "data_player_level", "label": 5, "begin": 6, "primkey": "id", "syntax": "off"}
, "achieve": {"description": "成就系统配置表", "output": "../../doc/trunk/game_server/data_achieve.config", "workbook": "../../doc/trunk/RE0_achieve.xlsm", "sheet": "data_achieve", "label": 5, "begin": 6, "primkey": "achieve_id", "syntax": "off"}
, "mail_template": {"description": "邮件系统配置表", "output": "../../doc/trunk/game_server/data_mail_template.config", "workbook": "../../doc/trunk/RE0_mail_template.xlsm", "sheet": "data_mail_template", "label": 5, "begin": 6, "primkey": "id", "syntax": "off"}
, "sensitive_words": {"description": "敏感词配置表", "output": "../../doc/trunk/game_server/data_sensitive_words.config", "workbook": "../../doc/trunk/RE0_sensitive_words.xlsm", "sheet": "data_sensitive_words", "label": 5, "begin": 6, "primkey": "id", "syntax": "off"}
, "intimacy_uplevel": {"description": "好感度升级配置表", "output": "../../doc/trunk/game_server/data_intimacy_uplevel.config", "workbook": "../../doc/trunk/RE0_role_intimacy_uplevel.xlsm", "sheet": "data_role_intimacy_uplevel", "label": 5, "begin": 6, "primkey": "primkey", "syntax": "off"}
, "intimacy_gift": {"description": "好感度礼物配置表", "output": "../../doc/trunk/game_server/data_intimacy_gift.config", "workbook": "../../doc/trunk/RE0_role_intimacy_gift.xlsm", "sheet": "data_role_intimacy_gift", "label": 5, "begin": 6, "primkey": "type_id", "syntax": "off"}
, "scene": {"description": "场景配置表", "output": "../../doc/trunk/game_server/data_scene.config", "workbook": "../../doc/trunk/RE0_scene.xlsm", "sheet": "data_scene", "label": 5, "begin": 6, "primkey": "type_id", "syntax": "off"}
, "collection": {"description": "cg动画音乐资源配置表", "output": "../../doc/trunk/game_server/data_collection.config", "workbook": "../../doc/trunk/RE0_collection.xlsm", "sheet": "data_collection", "label": 5, "begin": 6, "primkey": "type_id", "syntax": "off"}
, "shop": {"description": "商店配置表", "output": "../../doc/trunk/game_server/data_shop.config", "workbook": "../../doc/trunk/RE0_shop.xlsm", "sheet": "data_shop", "label": 5, "begin": 6, "primkey": "primkey", "syntax": "off"}
, "goods": {"description": "商品配置表", "output": "../../doc/trunk/game_server/data_goods.config", "workbook": "../../doc/trunk/RE0_goods.xlsm", "sheet": "data_goods", "label": 5, "begin": 6, "primkey": "primkey", "syntax": "off"}
, "intimacy_section": {"description": "好感度剧情配置表", "output": "../../doc/trunk/game_server/data_intimacy_section.config", "workbook": "../../doc/trunk/RE0_role_intimacy_section.xlsm", "sheet": "data_role_intimacy_section", "label": 5, "begin": 6, "primkey": "section_id", "syntax": "off"}
, "inform": {"description": "公告配置表", "output": "../../doc/trunk/game_server/data_inform.config", "workbook": "../../doc/trunk/RE0_inform.xlsm", "sheet": "data_inform", "label": 5, "begin": 6, "primkey": "primkey", "syntax": "off"}
, "player_head": {"description": "玩家头像配置表", "output": "../../doc/trunk/game_server/data_head.config", "workbook": "../../doc/trunk/RE0_player_head.xlsm", "sheet": "data_player_head", "label": 5, "begin": 6, "primkey": "id", "syntax": "off"}
, "pay": {"description": "充值配置表", "output": "../../doc/trunk/game_server/data_pay.config", "workbook": "../../doc/trunk/RE0_pay.xlsm", "sheet": "data_pay", "label": 5, "begin": 6, "primkey": "pay_id", "syntax": "off"}
, "task": {"description": "任务配置表", "output": "../../doc/trunk/game_server/data_task.config", "workbook": "../../doc/trunk/RE0_task.xlsm", "sheet": "data_task", "label": 5, "begin": 6, "primkey": "task_id", "syntax": "off"}
, "boss": {"description": "世界boss配置表", "output": "../../doc/trunk/game_server/data_boss.config", "workbook": "../../doc/trunk/RE0_boss.xlsm", "sheet": "data_boss", "label": 5, "begin": 6, "primkey": "boss_id", "syntax": "off"}
, "robot": {"description": "机器人配置表", "output": "../../doc/trunk/game_server/data_robot.config", "workbook": "../../doc/trunk/RE0_robot.xlsm", "sheet": "data_robot", "label": 5, "begin": 6, "primkey": "role_id", "syntax": "off"}
, "train": {"description": "特训配置表", "output": "../../doc/trunk/game_server/data_train.config", "workbook": "../../doc/trunk/RE0_train.xlsm", "sheet": "data_train", "label": 5, "begin": 6, "primkey": "train_id", "syntax": "off"}
, "sign": {"description": "签到配置表", "output": "../../doc/trunk/game_server/data_sign.config", "workbook": "../../doc/trunk/RE0_sign.xlsm", "sheet": "data_sign", "label": 5, "begin": 6, "primkey": "id", "syntax": "off"}
, "skill": {"description": "技能配置表", "output": "../../doc/trunk/game_server/data_skill.config", "workbook": "../../doc/trunk/RE0_skill.xlsm", "sheet": "data_skill", "label": 5, "begin": 6, "primkey": "id", "syntax": "off"}
, "card_pool": {"description": "抽卡产出配置表", "output": "../../doc/trunk/game_server/data_card_pool.config", "workbook": "../../doc/trunk/RE0_card_pool.xlsm", "sheet": "data_card_pool", "label": 5, "begin": 6, "primkey": "draw_id", "syntax": "off"}
, "clientconfig": {"description": "客户端杂项配置表", "output": "../../doc/trunk/game_server/data_clientconfig.config", "workbook": "../../doc/trunk/RE0_clientconfig.xlsm", "sheet": "data_clientconfig", "label": 5, "begin": 6, "primkey": "id", "syntax": "off"}
, "buy_gold": {"description": "购买金币配置表", "output": "../../doc/trunk/game_server/data_buy_gold.config", "workbook": "../../doc/trunk/RE0_buy_gold.xlsm", "sheet": "data_buy_gold", "label": 5, "begin": 6, "primkey": "count", "syntax": "off"},
"rehearse": {"description": "演练所配置表", "output": "../../doc/trunk/game_server/data_drillroom.config", "workbook": "../../doc/trunk/RE0_rehearse.xlsm", "sheet": "data_rehearse", "label": 5, "begin": 6, "primkey": "npc_id", "syntax": "off"},
"rehearse_time": {"description": "演练所阶段配置表", "output": "../../doc/trunk/game_server/data_drillroom_period.config", "workbook": "../../doc/trunk/RE0_rehearse_time.xlsm", "sheet": "data_rehearse_time", "label": 5, "begin": 6, "primkey": "time_id", "syntax": "off"}
, "global": {"description": "全局变量配置表", "output": "../../doc/trunk/game_server/data_global.config", "workbook": "../../doc/trunk/RE0_global.xlsm", "sheet": "data_global", "label": 5, "begin": 6, "primkey": "id", "syntax": "off"}
, "whitelist": {"description": "玩家白名单配置表", "output": "../../doc/trunk/game_server/data_whitelist.config", "workbook": "../../doc/trunk/RE0_whitelist.xlsm", "sheet": "data_whitelist", "label": 5, "begin": 6, "primkey": "id", "syntax": "off"}
, "player_headframe":{"description": "玩家头像框配置表", "output": "../../doc/trunk/game_server/data_head_frame.config", "workbook": "../../doc/trunk/RE0_player_headframe.xlsm", "sheet": "data_player_headframe", "label": 5, "begin": 6, "primkey": "id", "syntax": "off"}
, "meteor": {"description": "魔法器配置表", "output": "../../doc/trunk/game_server/data_meteor.config", "workbook": "../../doc/trunk/RE0_meteor.xlsm", "sheet": "data_meteor", "label": 5, "begin": 6, "primkey": "meteor_id", "syntax": "off"}
, "meteor_attr": {"description": "魔法器属性配置表", "output": "../../doc/trunk/game_server/data_meteor_attr.config", "workbook": "../../doc/trunk/RE0_meteor_attr.xlsm", "sheet": "data_meteor_attr", "label": 5, "begin": 6, "primkey": "id", "syntax": "off"}
, "activity": {"description": "活动入口配置表", "output": "../../doc/trunk/game_server/data_activity.config", "workbook": "../../doc/trunk/RE0_activity.xlsm", "sheet": "data_activity", "label": 5, "begin": 6, "primkey": "id", "syntax": "off"}
, "chest": {"description": "礼包宝箱配置表", "output": "../../doc/trunk/game_server/data_chest.config", "workbook": "../../doc/trunk/RE0_chest.xlsm", "sheet": "data_chest", "label": 5, "begin": 6, "primkey": "primkey", "syntax": "off"}
, "function_entry": {"description": "功能开放配置表", "output": "../../doc/trunk/game_server/data_function_entry.config", "workbook": "../../doc/trunk/RE0_function_entry.xlsm", "sheet": "data_function_entry", "label": 5, "begin": 6, "primkey": "id", "syntax": "off"}
}


